name: json_file
description: Fast and memory friendly access to large JSON files
version: 0.1.1
homepage: https://github.com/appsup-dart/json_file
repository: https://github.com/appsup-dart/json_file

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.8.0
  json_path: '>=0.5.0 <0.9.0'
  args: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.21.0
  file: ^7.0.0
  melos: ^7.0.0

melos:
  useRootAsPackage: true

  ide:
    intellij: false

  command:
    version:
      linkToCommits: true
      workspaceChangelog: false

  scripts:
    preversion: 
      exec: dart test -j 1  

executables:
  djq: djq
